### ISSUE TITLE
Not working on version 0.176.0

### ISSUE THREAD

**Issue by fabiode** [aergonaut/atom-erb#5]
Hey, since the last update in Atom, the keymap stopped working, but the command Atom: Atom-erb using the Command Pallete (cmd+shift+p) still works. Anyone is experiencing this as well?

**Comment by dcalhoun** [comment]
@fabiode the keybinding is working fine for me  in Atom 0.179.0. Is the keybinding still listed in atom-erb's preference pane? Could you possibly have another package enabled that is causing a conflict?

**Comment by fabiode** [comment]
Hi @dcalhoun !
Here is how it looks:
![image](https://cloud.githubusercontent.com/assets/916839/6335159/36ef6104-bb78-11e4-97a4-7b9512f0e242.png)

I've searched for other packages which would have any conflicting commands, but I didn't found any of them.

I'm going to to disable all packages and if works, I'll let you know!

Thanks!

**Comment by fabiode** [comment]
Just disabled all other packages and still no good...

**Comment by fabiode** [comment]
Hey, I've done a clean install from atom and the atom-erb package, now it's back to work! Thanks for your attention, @dcalhoun , I'm closing the issue.
